### ISSUE TITLE
请问hardware_param里面的onchip_buffer指的是哪部分的size？

### ISSUE THREAD

**Issue by pangsg** [hahnyuan/LLM-Viewer#10]
我查了一下资料，v100的L1和SRAM大小一共是128KB，但是repo里面写的V100 onchip_buffer是20480e3，这块想请教下指的是哪部分buffer

**Comment by hahnyuan** [comment]
Please see the chart in https://images.nvidia.com/content/volta-architecture/pdf/volta-architecture-whitepaper.pdf Page 10. The V100 has 20480 KB register file.

**Comment by pangsg** [comment]
thanks a lot.



---原始邮件---
发件人: "Zhihang ***@***.***&gt;
发送时间: 2024年7月16日(周二) 下午4:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hahnyuan/LLM-Viewer] 请问hardware_param里面的onchip_buffer指的是哪部分的size？ (Issue #10)




 
Please see the chart in https://images.nvidia.com/content/volta-architecture/pdf/volta-architecture-whitepaper.pdf Page 10. The V100 has 20480 KB register file.
