### ISSUE TITLE
I am not sure why OPs for softmax is "softmax_OPs = bsz * n_heads * seqlen * 1 * 5"

### ISSUE THREAD

**Issue by erxiong0** [hahnyuan/LLM-Viewer#11]
Why multiply 5?

**Comment by hahnyuan** [comment]
This is because the softmax operation takes five steps:
1. max_x=max(x)
2. x=x-max_x
3. x_exp=exp(x)
4. sum_x_exp=sum(x_exp)
5. y=x_exp/sum(x_exp)
